### ISSUE TITLE
Error when installing express-cdn

### ISSUE THREAD

**Issue by zilions** [niftylettuce/express-cdn#101]
I recieve the following error when attempting to install `express-cdn`:

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "express-cdn"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE

npm ERR! optipng-bin@0.3.11 postinstall: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the optipng-bin@0.3.11 postinstall script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the optipng-bin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs optipng-bin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls optipng-bin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Jade/Documents/nodetest/nexus-node-api/npm-debug.log

**Comment by gagalago** [comment]
when I update optipng and jpegtran, cdn work again
see #105

**Comment by gagalago** [comment]
fixed in 0.2.9
