### ISSUE TITLE
When Uglify fails, it doesn't tell which file is failing it.

### ISSUE THREAD

**Issue by nusantara-cloud** [niftylettuce/express-cdn#113]
I've found Uglify to fail for several good reasons:
1. ES6 code accidentally is used in JS assets
2. Static checked catches an error in JS code. (e.g. forgetting to close parenthesis)

When such failure happens, however, express-cdn doesn't print out which file fails.

![image](https://user-images.githubusercontent.com/32732766/31924472-bcb10daa-b8ab-11e7-9959-f9a221ba77c4.png)

**Comment by niftylettuce** [comment]
fixed in v0.3.3, see #120
