### ISSUE TITLE
Older version of clean-css leaving truncated files

### ISSUE THREAD

**Issue by ChrisHughes** [niftylettuce/express-cdn#116]
Was finding partial css saved to my CDN with no errors or warnings. After some troubleshooting, found that clean-css was silently failing. The cause was a Google Fonts @include statement, specifiaclly

```
@import url('https://fonts.googleapis.com/css?family=Josefin+Sans:100,300,400,600,800;|Open+Sans:300,400,600;');
```

I've submitted a pull request updating to the latest clean-css version where this issue has been fixed.

**Comment by niftylettuce** [comment]
released in v0.3.1, sorry didn't see this till now 😞 

`npm install express-cdn@latest` or `yarn add express-cdn@latest`
