### ISSUE TITLE
Getting error after latest update

### ISSUE THREAD

**Issue by jjg77** [niftylettuce/express-cdn#118]
"mime.lookup is not a function"

express-cdn@0.3.1

**Comment by niftylettuce** [comment]
@jjg77 I have published v0.3.2 to npm, please try it out and let me know if that fixes it for you? `npm install express-cdn@latest` or `yarn add express-cdn@latest` if you're using yarn.

**Comment by jjg77** [comment]
Error went away, but now it uploads blank files.
