### ISSUE TITLE
File file.js comes to S3 without content.

### ISSUE THREAD

**Issue by Gentos** [niftylettuce/express-cdn#119]
File file.js comes to S3 without content. In the logs shows the same as for the other files that come with the content.
{ task: 'express-cdn',
  message: '"js/file.js" was not found on S3 or was modified recently' }
{ task: 'express-cdn',
  message: '"css/file.min.css" was not found on S3 or was modified recently' }

At first I thought that it was not going through the minification and that's why the file comes without content, but I replaced the contents of this file with the code that passed the minification, the result is the same.

**Comment by ddemid** [comment]
https://github.com/niftylettuce/express-cdn/issues/120

**Comment by niftylettuce** [comment]
fixed in v0.3.3, see #120
