### ISSUE TITLE
0.31 and 0.32 releases are broken by UglifyJS 3.X

### ISSUE THREAD

**Issue by ddemid** [niftylettuce/express-cdn#120]
It silently fails to minify the js and uploads empty file to s3.

Since 0.31 you've upgraded to uglifyjs 3.X in package.json, which is being incorrectly used.

`var final_code = uglify.minify(results, {
            fromString: true,
            output: {
              comments: /license/
            }
          }).code;`

gives undefined as a result. And since you aren't checking the error property, it fails silently.

The real error message is:

> "fromString" is not a supported option node

**Comment by ddemid** [comment]
https://github.com/niftylettuce/express-cdn/pull/121

**Comment by niftylettuce** [comment]
thanks @ddemid - I have deprecated v0.3.1 and v0.3.2 with the message `Please upgrade to v0.3.3+ as this version is broken, see https://github.com/niftylettuce/express-cdn/issues/120`, and published v0.3.3

please `npm install express-cdn@latest` or `yarn add express-cdn@latest`.

appreciate your PR and bug finding.
