### ISSUE TITLE
Command to upload on build time instead of run time

### ISSUE THREAD

**Issue by Almad** [niftylettuce/express-cdn#30]
I'd like to avoid the "warming up" period when assets are being uploaded to S3.

Is there a way to invoke the upload on build time, so I can then just switch to another version of the app on production?

**Comment by charlesdg** [comment]
For grunt, use this:

```javascript
const done     = this.async();
const CDN      = require("express-cdn")(app, cdnOptions, done);
app.locals.CDN = CDN();
```
