### ISSUE TITLE
Support for Handlebars.js

### ISSUE THREAD

**Issue by heymichaelp** [niftylettuce/express-cdn#63]
I'm wondering what the recommended method of integration into [handlebars.js](http://handlebarsjs.com/) is.  The examples outlined in the `README.md` only outline implementations in Jade and EJS, but my site uses Handlebars templates.  I see that on this line: https://github.com/niftylettuce/express-cdn/blob/master/lib/main.js#L514, you reference only two valid extensions - does this mean there isn't support for any templating language other than these two?  If so, this should be made explicit in the `README.md`

**Comment by payam-meshkati-locm** [comment]
No support for handlebars?

**Comment by utsavkesharwani** [comment]
@niftylettuce: Was this done? Is handlebars supported? :crossed_fingers:
