### ISSUE TITLE
Probable n00b question: install errors and failure to upload

### ISSUE THREAD

**Issue by chasrmartin** [niftylettuce/express-cdn#65]
Following some emergency fixes for heartbleed, I'm having some problems I'm guessing have to do with a newer express-cdn version.  When I build the package for our (hitherto working) code, I get several errors to this effect:

```
npm WARN unmet dependency /home/ubuntu/sumazi/front/node_modules/express-cdn/node_modules/optipng-bin/node_modules/bin-wrapper/node_modules/bin-check requires executable@'^0.1.0' but will load
npm WARN unmet dependency /home/ubuntu/sumazi/front/node_modules/express-cdn/node_modules/optipng-bin/node_modules/bin-wrapper/node_modules/executable,
npm WARN unmet dependency which is version 0.1.1
npm WARN unmet dependency /home/ubuntu/sumazi/front/node_modules/express-cdn/node_modules/optipng-bin/node_modules/bin-wrapper/node_modules/bin-check requires win-spawn@'^2.0.0' but will load
npm WARN unmet dependency /home/ubuntu/sumazi/front/node_modules/express-cdn/node_modules/optipng-bin/node_modules/win-spawn,
npm WARN unmet dependency which is version 2.0.0
npm WARN unmet dependency /home/ubuntu/sumazi/front/node_modules/express-cdn/node_modules/optipng-bin/node_modules/bin-wrapper/node_modules/download/node_modules/decompress requires mkdirp@'^0.3.5' but will load
npm WARN unmet dependency /home/ubuntu/sumazi/front/node_modules/express-cdn/node_modules/optipng-bin/node_modules/bin-wrapper/node_modules/download/node_modules/mkdirp
```

Followed by a bunch of these:

```
 task: 'express-cdn',
  message: '"scripts/dashboard.models.js" was not found on S3 or was modified recently' }
{ task: 'express-cdn',
  message: '"scripts/dashboard.views.js" was not found on S3 or was modified recently' }
{ task: 'express-cdn',
  message: '"scripts/jquery.textsearch.js" was not found on S3 or was modified recently' }
{ task: 'express-cdn',
```

and then a bunch of these

```
unsuccessful upload of script "scripts/jquery.ui.js" to S3
unsuccessful upload of script "scripts/less.js" to S3
unsuccessful upload of script "scripts/jquery.waypoints.js" to S3
unsuccessful upload of script "scripts/jquery.validity.js" to S3
unsuccessful upload of script "scripts/sumazi.validation.js" to S3
unsuccessful upload of script "scripts/bootstrap-switch.js" to S3
```

It appears clear that I'm not able to get to the S3 bucket for some reason.  The secret and key are correct.  

This is inherited code that I don't know very well; guidance would be **very** helpful.

**Comment by chasrmartin** [comment]
Okay, so I'm no longer working for the company I did this for; they had their node server instance retired, and helping them out, I got it restarted. I'm having the same issue about being unable to load scripts to the CDN. I've checked and the API keys are current, and match.

Frankly, their use case no longer requires a CDN and I think the long term fix might be to just get rid of it. Does anyone have any honts on how to do that with the least damage?

**Comment by papaiatis** [comment]
Having the same problem:

```
Error: CDN: unsuccessful upload of script "images/company.png" to S3
    at throwError (/home/atis/WS/node-3tier-app/node_modules/express-cdn/lib/main.js:34:9)
    at /home/atis/WS/node-3tier-app/node_modules/express-cdn/lib/main.js:183:9
    at f (/home/atis/WS/node-3tier-app/node_modules/once/once.js:25:25)
    at ClientRequest.<anonymous> (/home/atis/WS/node-3tier-app/node_modules/knox/lib/client.js:51:5)
    at ClientRequest.emit (events.js:189:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:442:20)
    at TLSSocket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
```

How did you guys resolve it? Manual upload of files with `aws s3 cp` works just fine.

**Comment by vlad-snitsarenko** [comment]
> Having the same problem:
> 
> ```
> Error: CDN: unsuccessful upload of script "images/company.png" to S3
>     at throwError (/home/atis/WS/node-3tier-app/node_modules/express-cdn/lib/main.js:34:9)
>     at /home/atis/WS/node-3tier-app/node_modules/express-cdn/lib/main.js:183:9
>     at f (/home/atis/WS/node-3tier-app/node_modules/once/once.js:25:25)
>     at ClientRequest.<anonymous> (/home/atis/WS/node-3tier-app/node_modules/knox/lib/client.js:51:5)
>     at ClientRequest.emit (events.js:189:13)
>     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
>     at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
>     at TLSSocket.socketOnData (_http_client.js:442:20)
>     at TLSSocket.emit (events.js:189:13)
>     at addChunk (_stream_readable.js:284:12)
> ```
> 
> How did you guys resolve it? Manual upload of files with `aws s3 cp` works just fine.

Hi
For me problems was related to retry library and s3 bucket limitations (response 503)
Fixed that with this
node_modules/express-cdn/lib/main.js
```
    var operation = retry.operation({
      forever: true,
    });
      var req = S3.putBuffer(buffer, fileName, headers, function(err, response) {
// here is the problem that operation.retry returns false cuz no error provided
        if (operation.retry(err ?  err : response.statusCode === 503 ? {error:'503'}: null)) { return; }
        if (response.statusCode === 200) {
          return finishUpload();
        }
        if (err) {
          return throwError(operation.mainError());
        }
        throwError('unsuccessful upload of script "' + fileName + '" to S3');
      });
```
