### ISSUE TITLE
How to call CDN function from express app.js instead of in view?

### ISSUE THREAD

**Issue by timelf123** [niftylettuce/express-cdn#90]
We have a custom script bundler that adds bundles of scripts to our view. This is done with an ejs helper that steps through each bundle array and writes a new line for each script, or in production, the concatenated script bundle.

example bundle ejs helper in app.js
```
app.locals.ScriptBundle = function(bundleName) {
    var scriptBundle = bundleConfig.getScriptBundleByName(bundleName);

    if (config.nodeEnv != "production") {
        var arrayOfScripts = scriptBundle ? scriptBundle.files : [];

        var tags = arrayOfScripts.map(function(
            return '<script src="' + script.replace("public", "") + '"></script>';
        })

        return tags.join("\n");
    } else {
        var bundleNameMin = scriptBundle.name.replace(".js", ".min.js");
        return '<script src="/distribution/app/' + bundleNameMin + '"></script>';
    }
}
```

Bundle example that the above code steps through
```
    applicationScripts: {
        name: "application.js",
        files: [
            "public/app/app.js",
            "public/app/animations.js",
            "public/app/filters.js"
        ],
    }
```

Referenced in view:
```
<%- ScriptBundle('applicationScripts') %>
```

If possible what I'm looking for is a way to run the CDN function over them in our bundler that lives in app.js, rather than in the view. I tried having the bundler write `<% CDN(filename) %>` instead of `<script>` tags but I end up with static html instead of the bundler running.

Something like this:
```
app.locals.StyleBundle = function(bundleName) {
    var styleBundle = bundleConfig.getStyleBundleByName(bundleName);
    var arrayOfScripts = styleBundle ? styleBundle.files : [];
    return CDN(arrayOfScripts);
}
```

**Comment by niftylettuce** [comment]
Just read the code and then you can pass and run it manually I'm sure:

https://github.com/niftylettuce/express-cdn/blob/master/lib/main.js#L543

Pass options/arguments to that CDN function

You could open up your node_modules/express-cdn/lib/main.js file locally and add console.log everywhere in that function in order to track what its doing.
