### ISSUE TITLE
Concatenating files doesn't produce a URL-encoded CDN address

### ISSUE THREAD

**Issue by tsestrich** [niftylettuce/express-cdn#95]
I'm using Express CDN with the SWIG templating engine, but I don't think that is impacting my result here.

When I concatenate files based on the documentation, I am getting a properly concatenated file that is uploaded to S3. That part works fine. It is given an object name on S3 of something like "file1+file2+file3.js".

When it inserts the new fully-formed script tag into the HTML, it is providing a URL matching this exact string (".../file1+file2+file3.js"). However, S3 is rejecting this request as denied, because S3 expects the request to be URL encoded. The examples in the documentation even indicate that the resulting URL should be something like "https://cdn.your-site.com/plugins%2Bscript.1341382571.js", with the "+" encoded to "%2B".

What am I missing here?

In the meantime, I am writing a custom filter for SWIG that will do the URL encoding that is needed, after the fact.

**Comment by tsestrich** [comment]
For anyone that stumbles across this, here's the custom SWIG filter I wrote:

    swig.setFilter("url_encode_tag", function(tag){
        var hrefRegex = /href=["'](http.*cloudfront.net\/)(.*?)(\?.*?)["']/i;
        var srcRegex = /src=["'](http.*cloudfront.net\/)(.*?)(\?.*?)["']/i;
        
        if(tag.indexOf("src") >= 0)
        {
            var root = tag.match(srcRegex)[1];
            var src = tag.match(srcRegex)[2];
            var tail = tag.match(srcRegex)[3];
            var encoded = encodeURIComponent(src);
            tag = tag.replace(srcRegex, "src='" + root + encoded + tail + "'");
        }
        else if(tag.indexOf("href") >= 0)
        {
            var root = tag.match(hrefRegex)[1];
            var href = tag.match(hrefRegex)[2];
            var tail = tag.match(hrefRegex)[3];
            var encoded = encodeURIComponent(href);
            tag = tag.replace(hrefRegex, "href='" + root + encoded + tail + "'");
        }
        
        return tag;
    });

Use it like this:

    {{ CDN(['/css/first.css',
                    '/css/second.css',
                    '/css/third.css',
                    '/css/fourth.css'])|url_encode_tag }}

**Comment by niftylettuce** [comment]
released in v0.3.1, sorry didn't see this till now 😞 

`npm install express-cdn@latest` or `yarn add express-cdn@latest`
